export const chatsPlaceholderData = [
  {
    id: 1,
    title: 'Андрей',
    messageTime: '10:49',
    lastMessage: 'Изображение',
    unreadCount: 2,
  },
  {
    id: 2,
    title: 'Алексей',
    messageTime: '12:00',
    lastMessage: 'И Human Interface Guidelines и Material Design рекомендуют',
  },
  {
    id: 3,
    title: 'Илья',
    messageTime: '15:12',
    lastMessage: 'Друзья, у меня для вас особенный выпуск новостей!',
    unreadCount: 4,
  },
  {
    id: 4,
    title: '1,2,3',
    messageTime: 'Пн',
    lastMessage: 'Миллионы россиян ежедневно проводят десятки часов свое',
  },
  {
    id: 5,
    title: 'Design Destroyer',
    messageTime: 'Пн',
    lastMessage: 'В 2008 году художник Jon Rafman  начал собирать',
  },
  {
    id: 6,
    title: 'Day',
    messageTime: '1 Мая 2020',
    lastMessage: 'Так увлёкся работой по курсу, что совсем забыл его анонсир',
  },
  {
    id: 7,
    title: 'Стас Рогозин',
    messageTime: '12 Апр 2020',
    lastMessage: 'Можно или сегодня или завтра вечером',
  },
  {
    id: 8,
    title: 'Стас Рогозин',
    messageTime: '12 Апр 2020',
    lastMessage: 'Можно или сегодня или завтра вечером',
  },
  {
    id: 9,
    title: 'Стас Рогозин',
    messageTime: '12 Апр 2020',
    lastMessage: 'Можно или сегодня или завтра вечером',
  },
  {
    id: 10,
    title: 'Стас Рогозин',
    messageTime: '12 Апр 2020',
    lastMessage: 'Можно или сегодня или завтра вечером',
  },
  {
    id: 11,
    title: 'Стас Рогозин',
    messageTime: '12 Апр 2020',
    lastMessage: 'Можно или сегодня или завтра вечером',
  },
  {
    id: 12,
    title: 'Стас Рогозин',
    messageTime: '12 Апр 2020',
    lastMessage: 'Можно или сегодня или завтра вечером',
  },
]
